name: Main Java Pipeline

on: [push]

jobs:
  call-build:
    uses: SudheerNunna123/simple-java-maven-app-1/.github/workflows/reusable-java-build.yml@master


name: Reusable Java Build

on:
  workflow_call:  # Allows other workflows to call this

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11, 17]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test

      - name: Use GitHub Secret (API Key)
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Using API Key: $API_KEY"
