name: Reusable Java Builds

on:
  workflow_call:
    inputs:
      java_version:
        required: true
        type: string
    secrets:
      api_key:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure all files are fetched

      - name: List Directory Contents  # Debugging step
        run: ls -R

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java_version }}

      - name: Change to Project Directory and Build
        run: |
          cd /home/runner/work/simple-java-maven-app-1/simple-java-maven-app-1
          mvn clean install

  test:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Run Tests
        run: |
          cd /home/runner/work/simple-java-maven-app-1/simple-java-maven-app-1
          mvn test
