name: Reusable Java Builds  # This is a reusable workflow for building Java projects

on:
  workflow_call:  # Allows other workflows to call this one
    inputs:
      java_version:  # The Java version to use
        required: true
        type: string
    secrets:
      API_KEY:  # Secret key for authentication (must be provided)
        required: true

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    steps:
      - name: Checkout Code  # Pull the repo code
        uses: actions/checkout@v3

      - name: Set Up Java  # Install and configure Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use the Temurin Java distribution
          java-version: ${{ inputs.java_version }}  # Use the specified Java version

      - name: Build and Test  # Compile and test the project
        run: |
          mvn clean install  # Clean and build the project
          mvn test  # Run the tests

      - name: Use API Key  # Example of using a secret
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Set API key from secrets
        run: echo "Using API Key"  # Just printing a message (To avoid exposing secrets in logs)
